CONCEPTS = [
  'Truth',
  'Justice',
  'Purity',
  'Kindness',
  'Radiance',
  'Organic Growth',
  'Life after Death',
  'Love',
  'Devotion',
  'Sovereignty',
  'Unity',
  'Respect',
  'Cleanliness',
  'Forgiveness',
  'Humility',
  'Truthfulness',
  'Trustworthiness',
  'Reverence',
  'Service',
  'Patience',
  'Self-Discipline',
  'Joy',
  'Faith',
  'Gratefulness',
  'Detachment',
  'Detachment',
  'Gentleness',
  'Praiseworthy',
  'Creativity'
].freeze
